apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  username: "seu_usuario_rds"
  password: "sua_senha_rds"
  database: "nome_do_seu_banco_rds"
  host: "endpoint_do_seu_rds.amazonaws.com"
