name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite que o workflow seja acionado manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.14.9
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Apply
        id: terraform_apply
        run: |
          cd terraform
          terraform init -upgrade
          terraform apply -auto-approve\
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="database_name=${{ secrets.DATABASE_NAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}"
            DB_INSTANCE_ENDPOINT=$(terraform output -raw db_instance_endpoint | cut -d':' -f1)
            echo "DB_INSTANCE_ENDPOINT=$DB_INSTANCE_ENDPOINT" >> $GITHUB_ENV
            CLUSTER_NAME=$(terraform output -raw cluster_name)
            echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
        
      - name: Configure AWS EKS kubectl
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}
      
      - name: List EKS Nodes
        run: |
          kubectl get nodes

      - name: Configure Kubernetes Secrets
        run: |
          kubectl create secret generic postgres-secret \
            --from-literal=username=${{ secrets.DB_USERNAME }} \
            --from-literal=password=${{ secrets.DB_PASSWORD }} \
            --from-literal=database=${{ secrets.DATABASE_NAME }} \
            --from-literal=host=${{ env.DB_INSTANCE_ENDPOINT }} \
            --dry-run=client -o yaml | kubectl apply -f -
        working-directory: terraform

      - name: Deploy Kubernetes Configuration
        run: |
          kubectl apply -f kubernetes/api/1-api-deployment.yml
          kubectl apply -f kubernetes/api/2-api-service.yml
          kubectl apply -f kubernetes/api/3-api-hpa.yml
          kubectl apply -f kubernetes/apppagamento/1-api-pagamento-deployment.yml
          kubectl apply -f kubernetes/apppagamento/2-api-pagamento-service.yml
          kubectl apply -f kubernetes/apppagamento/3-api-pagamento-hpa.yml

      - name: Get API Service Public Address
        run: |
          echo "API_PUBLIC_ADDRESS=$(kubectl get svc api-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_ENV

      - name: Use API Public Address
        run: |
          echo "Accessing API at http://${{ env.API_PUBLIC_ADDRESS }}"          
